# Generated by Django 4.2.4 on 2023-08-25 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_customers_gender_alter_customers_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(default=12, max_length=100),
            preserve_default=False,
        ),
    ]
