# Generated by Django 4.2.4 on 2023-09-04 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_cartitem_cart_remove_cartitem_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='profile_picture',
            field=models.CharField(default=None, max_length=1000, null=True),
        ),
    ]
