# Generated by Django 4.2.4 on 2023-09-04 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userview', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
